- name: Deploy to EC2
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ec2-user
    key: ${{ secrets.EC2_KEY }}
    script: |
      IMAGE_TAG=${{ env.IMAGE_TAG }}
      ECR_REPO=${{ env.ECR_REPO }}
      CONTAINER_NAME=${{ env.CONTAINER_NAME }}
      PORT=${{ env.PORT }}

      ACCOUNT=$(echo $ECR_REPO | cut -d'.' -f1)
      REGISTRY="$ACCOUNT.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com"

      aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
      docker login --username AWS --password-stdin $REGISTRY

      docker pull $ECR_REPO:$IMAGE_TAG
      docker rm -f $CONTAINER_NAME || true
      docker run -d \
        --name $CONTAINER_NAME \
        -p $PORT:3000 \
        $ECR_REPO:$IMAGE_TAG